version: '3.8'

services:
  web:
    container_name: site-portfolio-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/portfolio?sslmode=disable
    depends_on:
      - db
    networks:
      - site-portfolio-network

  db:
    container_name: site-portfolio-db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio
    ports:
      - "5434:5432"
    networks:
      - site-portfolio-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  site-portfolio-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
